name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: pebble
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build pebble-tool
      run: nix-build -A packages.pebble-tool
    - name: Build pebble-qemu
      run: nix-build -A packages.pebble-qemu
    - name: Build pebbleEnv
      run: nix-shell -A pebbleEnv --run "echo OK"
