name: "Build"
on:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: pebble
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build pebble-tool
      run: nix build -L .#pebble-tool
    - name: Build pebble-qemu
      run: nix build -L .#pebble-qemu
    - name: Build pebbleEnv
      run: nix-shell -A pebbleEnv --run "echo OK"
